FROM python:3.11-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY source/llm_agent.py .

ENV FLASK_APP=llm_agent.py
ENV FLASK_ENV=production

EXPOSE 5001

CMD ["python", "llm_agent.py"]
