# Minimal full diarization config for NeMo ClusteringDiarizer
# Used as a local fallback when NeMo package does not ship YAML configs.

device: null
sample_rate: 16000
num_workers: 0
batch_size: 1
pin_memory: true
verbose: false

diarizer:
  manifest_filepath: null
  out_dir: null
  oracle_vad: false
  collar: 0.25
  ignore_overlap: false

  vad:
    model_path: vad_multilingual_marblenet
    external_vad_manifest: null
    parameters:
      window_length_in_sec: 0.15
      shift_length_in_sec: 0.01
      overlap: 0.5
      onset: 0.8
      offset: 0.6
      min_duration_on: 0.1
      min_duration_off: 0.3
      smoothing: median
      pad_onset: 0.0
      pad_offset: 0.0

  speaker_embeddings:
    model_path: titanet_large
    parameters:
      window_length_in_sec: [1.5, 1.0, 0.5]
      shift_length_in_sec: [0.75, 0.5, 0.25]
      multiscale_weights: [1.0, 1.0, 1.0]
      save_embeddings: false
      batch_size: 32

  clustering:
    parameters:
      oracle_num_speakers: true
      max_num_speakers: 2
      min_num_speakers: 2
      max_rp_threshold: 0.15
      sparse_search_volume: 30
      chunk_cluster_count: null
      embeddings_per_chunk: null
